vich_uploader:
    db_driver: orm

    mappings:
    # gestion des images
       aliment_image:
    # prefixe d'installation des images le    
           uri_prefix: /images/aliments
        #    la destination de l'image sur le serveur
           upload_destination: '%kernel.project_dir%/public/images/aliments'
