vich_uploader:
    db_driver: orm

    mappings:    
       aliment_image:
           uri_prefix: %image_aliment%
           upload_destination: '%kernel.project_dir%/public%image_aliment%'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
           
